title: My Long Haul Blog
email: youremail@example.com
description: >
  A simple blog powered by Jekyll and GitHub Pages.
baseurl: "" 
url: "https://yourusername.github.io"

remote_theme: brianmaierjr/long-haul

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
